// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: file.sql

package db

import (
	"context"
)

const getFile = `-- name: GetFile :one
SELECT id, bucket, name, organisation_id, created_at, deleted_at
FROM files
WHERE id = $1 AND organisation_id = $2
`

type GetFileParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.ID, arg.OrganisationID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Name,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
