// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/tabbed/pqtype"
)

type CompetenceType string

const (
	CompetenceTypeSubject    CompetenceType = "subject"
	CompetenceTypeGroup      CompetenceType = "group"
	CompetenceTypeCompetence CompetenceType = "competence"
)

func (e *CompetenceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompetenceType(s)
	case string:
		*e = CompetenceType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompetenceType: %T", src)
	}
	return nil
}

type NullCompetenceType struct {
	CompetenceType CompetenceType
	Valid          bool // Valid is true if CompetenceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompetenceType) Scan(value interface{}) error {
	if value == nil {
		ns.CompetenceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompetenceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompetenceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompetenceType), nil
}

type ReportStatus string

const (
	ReportStatusPending    ReportStatus = "pending"
	ReportStatusProcessing ReportStatus = "processing"
	ReportStatusDone       ReportStatus = "done"
	ReportStatusError      ReportStatus = "error"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ReportType string

const (
	ReportTypeReport       ReportType = "report"
	ReportTypeSubjects     ReportType = "subjects"
	ReportTypeReportDocx   ReportType = "report_docx"
	ReportTypeSubjectsDocx ReportType = "subjects_docx"
)

func (e *ReportType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportType(s)
	case string:
		*e = ReportType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportType: %T", src)
	}
	return nil
}

type NullReportType struct {
	ReportType ReportType
	Valid      bool // Valid is true if ReportType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportType) Scan(value interface{}) error {
	if value == nil {
		ns.ReportType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportType), nil
}

type UserRole string

const (
	UserRoleOwner    UserRole = "owner"
	UserRoleAdmin    UserRole = "admin"
	UserRoleTeacher  UserRole = "teacher"
	UserRoleEducator UserRole = "educator"
	UserRoleStudent  UserRole = "student"
	UserRoleParent   UserRole = "parent"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Chat struct {
	ID             string         `json:"id"`
	Name           sql.NullString `json:"name"`
	OrganisationID string         `json:"organisationID"`
	UpdatedAt      sql.NullTime   `json:"updatedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type ChatMessage struct {
	ID        string       `json:"id"`
	ChatID    string       `json:"chatID"`
	UserID    string       `json:"userID"`
	Message   string       `json:"message"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	CreatedAt time.Time    `json:"createdAt"`
}

type ChatMessageFile struct {
	ID        string       `json:"id"`
	ChatID    string       `json:"chatID"`
	UserID    string       `json:"userID"`
	MessageID string       `json:"messageID"`
	FileID    string       `json:"fileID"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	CreatedAt time.Time    `json:"createdAt"`
}

type ChatMessageReaction struct {
	ID        string    `json:"id"`
	ChatID    string    `json:"chatID"`
	UserID    string    `json:"userID"`
	MessageID string    `json:"messageID"`
	Reaction  string    `json:"reaction"`
	CreatedAt time.Time `json:"createdAt"`
}

type ChatUser struct {
	ChatID string `json:"chatID"`
	UserID string `json:"userID"`
}

type Competence struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	CompetenceID   sql.NullString `json:"competenceID"`
	CompetenceType CompetenceType `json:"competenceType"`
	OrganisationID string         `json:"organisationID"`
	Grades         []int32        `json:"grades"`
	Color          sql.NullString `json:"color"`
	CreatedAt      time.Time      `json:"createdAt"`
	DeletedAt      sql.NullTime   `json:"deletedAt"`
}

type Entry struct {
	ID             string          `json:"id"`
	Date           time.Time       `json:"date"`
	Body           json.RawMessage `json:"body"`
	UserID         string          `json:"userID"`
	CreatedAt      time.Time       `json:"createdAt"`
	DeletedAt      sql.NullTime    `json:"deletedAt"`
	OrganisationID string          `json:"organisationID"`
}

type EntryEvent struct {
	ID             string       `json:"id"`
	EntryID        string       `json:"entryID"`
	EventID        string       `json:"eventID"`
	OrganisationID string       `json:"organisationID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
}

type EntryFile struct {
	ID             string       `json:"id"`
	EntryID        string       `json:"entryID"`
	FileBucketID   string       `json:"fileBucketID"`
	FileName       string       `json:"fileName"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
	OrganisationID string       `json:"organisationID"`
}

type EntryTag struct {
	ID             string       `json:"id"`
	EntryID        string       `json:"entryID"`
	TagID          string       `json:"tagID"`
	OrganisationID string       `json:"organisationID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
}

type EntryUser struct {
	ID             string       `json:"id"`
	EntryID        string       `json:"entryID"`
	UserID         string       `json:"userID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
	OrganisationID string       `json:"organisationID"`
}

type EntryUserCompetence struct {
	ID             string       `json:"id"`
	Level          int32        `json:"level"`
	UserID         string       `json:"userID"`
	EntryID        string       `json:"entryID"`
	CompetenceID   string       `json:"competenceID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
	OrganisationID string       `json:"organisationID"`
}

type Event struct {
	ID                string         `json:"id"`
	ImageFileBucketID sql.NullString `json:"imageFileBucketID"`
	ImageFileName     sql.NullString `json:"imageFileName"`
	OrganisationID    string         `json:"organisationID"`
	Title             string         `json:"title"`
	Body              string         `json:"body"`
	StartsAt          time.Time      `json:"startsAt"`
	EndsAt            time.Time      `json:"endsAt"`
	Recurrence        []string       `json:"recurrence"`
	CreatedAt         time.Time      `json:"createdAt"`
	DeletedAt         sql.NullTime   `json:"deletedAt"`
}

type EventCompetence struct {
	ID             string       `json:"id"`
	EventID        string       `json:"eventID"`
	CompetenceID   string       `json:"competenceID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
	OrganisationID string       `json:"organisationID"`
}

type File struct {
	ID             string       `json:"id"`
	FileBucketID   string       `json:"fileBucketID"`
	FileName       string       `json:"fileName"`
	OrganisationID string       `json:"organisationID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
}

type Organisation struct {
	ID             string       `json:"id"`
	Name           string       `json:"name"`
	LegalName      string       `json:"legalName"`
	Website        string       `json:"website"`
	Phone          string       `json:"phone"`
	OwnerID        string       `json:"ownerID"`
	AllowedDomains []string     `json:"allowedDomains"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
}

type Report struct {
	ID             string                `json:"id"`
	FileBucketID   sql.NullString        `json:"fileBucketID"`
	FileName       sql.NullString        `json:"fileName"`
	Status         ReportStatus          `json:"status"`
	Type           ReportType            `json:"type"`
	From           time.Time             `json:"from"`
	To             time.Time             `json:"to"`
	UserID         string                `json:"userID"`
	StudentUserID  string                `json:"studentUserID"`
	Meta           pqtype.NullRawMessage `json:"meta"`
	CreatedAt      time.Time             `json:"createdAt"`
	DeletedAt      sql.NullTime          `json:"deletedAt"`
	FilterTags     []string              `json:"filterTags"`
	OrganisationID string                `json:"organisationID"`
}

type Tag struct {
	ID             string       `json:"id"`
	Name           string       `json:"name"`
	Color          string       `json:"color"`
	OrganisationID string       `json:"organisationID"`
	CreatedAt      time.Time    `json:"createdAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
}

type User struct {
	ID             string         `json:"id"`
	Role           UserRole       `json:"role"`
	OrganisationID string         `json:"organisationID"`
	FirstName      string         `json:"firstName"`
	LastName       string         `json:"lastName"`
	Email          sql.NullString `json:"email"`
	Password       sql.NullString `json:"password"`
	AvatarFile     sql.NullString `json:"avatarFile"`
	Birthday       sql.NullTime   `json:"birthday"`
	Grade          sql.NullInt32  `json:"grade"`
	LeftAt         sql.NullTime   `json:"leftAt"`
	JoinedAt       sql.NullTime   `json:"joinedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	DeletedAt      sql.NullTime   `json:"deletedAt"`
}
