// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry_user.sql

package db

import (
	"context"
)

const entryUserCountByUserID = `-- name: EntryUserCountByUserID :one
SELECT COUNT(*)
FROM entry_users
WHERE user_id = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type EntryUserCountByUserIDParams struct {
	UserID         string `db:"user_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) EntryUserCountByUserID(ctx context.Context, arg EntryUserCountByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, entryUserCountByUserID, arg.UserID, arg.OrganisationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
