// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry_events.sql

package db

import (
	"context"
)

const entryEventCreate = `-- name: EntryEventCreate :one
INSERT INTO entry_events (entry_id, event_id, organisation_id)
VALUES ($1, $2, $3)
ON CONFLICT (entry_id, event_id, organisation_id) DO UPDATE SET deleted_at = NULL
RETURNING id, entry_id, event_id, organisation_id, created_at, deleted_at
`

type EntryEventCreateParams struct {
	EntryID        string `db:"entry_id"`
	EventID        string `db:"event_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) EntryEventCreate(ctx context.Context, arg EntryEventCreateParams) (EntryEvent, error) {
	row := q.db.QueryRow(ctx, entryEventCreate, arg.EntryID, arg.EventID, arg.OrganisationID)
	var i EntryEvent
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.EventID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const entryEventSoftDelete = `-- name: EntryEventSoftDelete :one
UPDATE entry_events
SET deleted_at = NOW()
WHERE entry_id = $1
  AND event_id = $2
  AND organisation_id = $3
RETURNING id, entry_id, event_id, organisation_id, created_at, deleted_at
`

type EntryEventSoftDeleteParams struct {
	EntryID        string `db:"entry_id"`
	EventID        string `db:"event_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) EntryEventSoftDelete(ctx context.Context, arg EntryEventSoftDeleteParams) (EntryEvent, error) {
	row := q.db.QueryRow(ctx, entryEventSoftDelete, arg.EntryID, arg.EventID, arg.OrganisationID)
	var i EntryEvent
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.EventID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const entryEventsAll = `-- name: EntryEventsAll :many
SELECT id, entry_id, event_id, organisation_id, created_at, deleted_at
FROM entry_events
WHERE organisation_id = $1
`

func (q *Queries) EntryEventsAll(ctx context.Context, organisationID string) ([]EntryEvent, error) {
	rows, err := q.db.Query(ctx, entryEventsAll, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryEvent
	for rows.Next() {
		var i EntryEvent
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.EventID,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsFindByEntryEventEntryID = `-- name: EventsFindByEntryEventEntryID :many
SELECT events.id, events.image_file_id, events.organisation_id, events.title, events.body, events.starts_at, events.ends_at, events.recurrence, events.created_at, events.deleted_at
FROM events
         JOIN public.entry_events eu ON events.id = eu.event_id
         JOIN public.entries e ON eu.entry_id = e.id AND e.id = $1
WHERE events.organisation_id = $2
  AND eu.deleted_at IS NULL
  AND e.deleted_at IS NULL
  AND events.deleted_at IS NULL
`

type EventsFindByEntryEventEntryIDParams struct {
	EntryID        string `db:"entry_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) EventsFindByEntryEventEntryID(ctx context.Context, arg EventsFindByEntryEventEntryIDParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventsFindByEntryEventEntryID, arg.EntryID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ImageFileID,
			&i.OrganisationID,
			&i.Title,
			&i.Body,
			&i.StartsAt,
			&i.EndsAt,
			&i.Recurrence,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
