// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: organisation.sql

package db

import (
	"context"
)

const gLOBAL_OrganisationFindByID = `-- name: GLOBAL_OrganisationFindByID :one
SELECT id, name, legal_name, website, phone, owner_id, allowed_domains, enabled_apps, created_at, deleted_at, setup_complete, address, logo_url, stripe_customer_id, stripe_subscription_id FROM organisations WHERE id = $1
`

func (q *Queries) GLOBAL_OrganisationFindByID(ctx context.Context, id string) (Organisation, error) {
	row := q.db.QueryRow(ctx, gLOBAL_OrganisationFindByID, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalName,
		&i.Website,
		&i.Phone,
		&i.OwnerID,
		&i.AllowedDomains,
		&i.EnabledApps,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SetupComplete,
		&i.Address,
		&i.LogoUrl,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
	)
	return i, err
}
