// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: session.sql

package db

import (
	"context"
)

const gLOBAL_SessionCountByToken = `-- name: GLOBAL_SessionCountByToken :one
SELECT COUNT(*)
FROM sessions
WHERE token = $1
  AND deleted_at IS NULL
`

func (q *Queries) GLOBAL_SessionCountByToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, gLOBAL_SessionCountByToken, token)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const gLOBAL_SessionCountByUserId = `-- name: GLOBAL_SessionCountByUserId :one
SELECT COUNT(*)
FROM sessions
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GLOBAL_SessionCountByUserId(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, gLOBAL_SessionCountByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const gLOBAL_SessionCreate = `-- name: GLOBAL_SessionCreate :one
INSERT INTO sessions (user_id, token)
VALUES ($1, $2)
RETURNING id, user_id, token, created_at, deleted_at
`

type GLOBAL_SessionCreateParams struct {
	UserID string `db:"user_id"`
	Token  string `db:"token"`
}

func (q *Queries) GLOBAL_SessionCreate(ctx context.Context, arg GLOBAL_SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, gLOBAL_SessionCreate, arg.UserID, arg.Token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const gLOBAL_SessionDeleteExpired = `-- name: GLOBAL_SessionDeleteExpired :exec
UPDATE sessions
SET deleted_at = NOW()
WHERE created_at < NOW() - INTERVAL '12 hours'
`

func (q *Queries) GLOBAL_SessionDeleteExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, gLOBAL_SessionDeleteExpired)
	return err
}

const gLOBAL_SessionFindByToken = `-- name: GLOBAL_SessionFindByToken :one
SELECT id, user_id, token, created_at, deleted_at
FROM sessions
WHERE token = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GLOBAL_SessionFindByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, gLOBAL_SessionFindByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const gLOBAL_SessionsDeleteByUserID = `-- name: GLOBAL_SessionsDeleteByUserID :exec
UPDATE sessions
SET deleted_at = NOW()
WHERE user_id = $1
`

func (q *Queries) GLOBAL_SessionsDeleteByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, gLOBAL_SessionsDeleteByUserID, userID)
	return err
}

const gLOBAL_SessionsFindByUserID = `-- name: GLOBAL_SessionsFindByUserID :exec
UPDATE sessions
SET deleted_at = NOW()
WHERE user_id = $1
`

func (q *Queries) GLOBAL_SessionsFindByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, gLOBAL_SessionsFindByUserID, userID)
	return err
}
