// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_competence.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const rEPORT_UserCompetenceListByUserId = `-- name: REPORT_UserCompetenceListByUserId :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE user_id = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
  AND created_at >= $3
  AND created_at <= (DATE $4 + 1)
ORDER BY created_at DESC
`

type REPORT_UserCompetenceListByUserIdParams struct {
	UserID         string    `db:"user_id"`
	OrganisationID string    `db:"organisation_id"`
	StartDate      time.Time `db:"start_date"`
	EndDate        time.Time `db:"+end_date"`
}

func (q *Queries) REPORT_UserCompetenceListByUserId(ctx context.Context, arg REPORT_UserCompetenceListByUserIdParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, rEPORT_UserCompetenceListByUserId,
		arg.UserID,
		arg.OrganisationID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceCompetenceListByEntry = `-- name: UserCompetenceCompetenceListByEntry :many
SELECT competences.id, name, competences.competence_id, competence_type, competences.organisation_id, grades, color, curriculum_id, competences.created_at, competences.deleted_at, sort_order, competences.created_by, uc.id, level, uc.user_id, entry_id, uc.competence_id, uc.created_at, uc.created_by, uc.deleted_at, uc.organisation_id, e.id, date, body, e.user_id, e.created_at, e.deleted_at, e.organisation_id
FROM competences
         JOIN public.user_competences uc ON competences.id = uc.competence_id
         JOIN public.entries e ON uc.entry_id = e.id
WHERE uc.user_id = $1
  AND uc.organisation_id = $2
  AND uc.entry_id = $3
  AND uc.deleted_at IS NULL
  AND e.deleted_at IS NULL
  AND competences.deleted_at IS NULL
`

type UserCompetenceCompetenceListByEntryParams struct {
	UserID         string      `db:"user_id"`
	OrganisationID string      `db:"organisation_id"`
	EntryID        pgtype.Text `db:"entry_id"`
}

type UserCompetenceCompetenceListByEntryRow struct {
	ID               string             `db:"id"`
	Name             string             `db:"name"`
	CompetenceID     pgtype.Text        `db:"competence_id"`
	CompetenceType   CompetenceType     `db:"competence_type"`
	OrganisationID   string             `db:"organisation_id"`
	Grades           []int32            `db:"grades"`
	Color            pgtype.Text        `db:"color"`
	CurriculumID     pgtype.Text        `db:"curriculum_id"`
	CreatedAt        time.Time          `db:"created_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
	SortOrder        pgtype.Int4        `db:"sort_order"`
	CreatedBy        pgtype.Text        `db:"created_by"`
	ID_2             string             `db:"id_2"`
	Level            int32              `db:"level"`
	UserID           string             `db:"user_id"`
	EntryID          pgtype.Text        `db:"entry_id"`
	CompetenceID_2   string             `db:"competence_id_2"`
	CreatedAt_2      time.Time          `db:"created_at_2"`
	CreatedBy_2      pgtype.Text        `db:"created_by_2"`
	DeletedAt_2      pgtype.Timestamptz `db:"deleted_at_2"`
	OrganisationID_2 string             `db:"organisation_id_2"`
	ID_3             string             `db:"id_3"`
	Date             pgtype.Date        `db:"date"`
	Body             string             `db:"body"`
	UserID_2         string             `db:"user_id_2"`
	CreatedAt_3      time.Time          `db:"created_at_3"`
	DeletedAt_3      pgtype.Timestamptz `db:"deleted_at_3"`
	OrganisationID_3 string             `db:"organisation_id_3"`
}

func (q *Queries) UserCompetenceCompetenceListByEntry(ctx context.Context, arg UserCompetenceCompetenceListByEntryParams) ([]UserCompetenceCompetenceListByEntryRow, error) {
	rows, err := q.db.Query(ctx, userCompetenceCompetenceListByEntry, arg.UserID, arg.OrganisationID, arg.EntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetenceCompetenceListByEntryRow
	for rows.Next() {
		var i UserCompetenceCompetenceListByEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CompetenceID,
			&i.CompetenceType,
			&i.OrganisationID,
			&i.Grades,
			&i.Color,
			&i.CurriculumID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.SortOrder,
			&i.CreatedBy,
			&i.ID_2,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID_2,
			&i.CreatedAt_2,
			&i.CreatedBy_2,
			&i.DeletedAt_2,
			&i.OrganisationID_2,
			&i.ID_3,
			&i.Date,
			&i.Body,
			&i.UserID_2,
			&i.CreatedAt_3,
			&i.DeletedAt_3,
			&i.OrganisationID_3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceCountByUserID = `-- name: UserCompetenceCountByUserID :one
SELECT COUNT(*)
FROM user_competences
WHERE user_id = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type UserCompetenceCountByUserIDParams struct {
	UserID         string `db:"user_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) UserCompetenceCountByUserID(ctx context.Context, arg UserCompetenceCountByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, userCompetenceCountByUserID, arg.UserID, arg.OrganisationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userCompetenceCreate = `-- name: UserCompetenceCreate :one
INSERT INTO user_competences (level, user_id, competence_id, entry_id, created_by, organisation_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, competence_id, entry_id) DO UPDATE SET deleted_at = NULL AND level = $1
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetenceCreateParams struct {
	Level          int32       `db:"level"`
	UserID         string      `db:"user_id"`
	CompetenceID   string      `db:"competence_id"`
	EntryID        pgtype.Text `db:"entry_id"`
	CreatedBy      pgtype.Text `db:"created_by"`
	OrganisationID string      `db:"organisation_id"`
}

func (q *Queries) UserCompetenceCreate(ctx context.Context, arg UserCompetenceCreateParams) (UserCompetence, error) {
	row := q.db.QueryRow(ctx, userCompetenceCreate,
		arg.Level,
		arg.UserID,
		arg.CompetenceID,
		arg.EntryID,
		arg.CreatedBy,
		arg.OrganisationID,
	)
	var i UserCompetence
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.UserID,
		&i.EntryID,
		&i.CompetenceID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.OrganisationID,
	)
	return i, err
}

const userCompetenceCreateWithoutEntry = `-- name: UserCompetenceCreateWithoutEntry :one
INSERT INTO user_competences (level, user_id, competence_id, created_by, organisation_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetenceCreateWithoutEntryParams struct {
	Level          int32       `db:"level"`
	UserID         string      `db:"user_id"`
	CompetenceID   string      `db:"competence_id"`
	CreatedBy      pgtype.Text `db:"created_by"`
	OrganisationID string      `db:"organisation_id"`
}

func (q *Queries) UserCompetenceCreateWithoutEntry(ctx context.Context, arg UserCompetenceCreateWithoutEntryParams) (UserCompetence, error) {
	row := q.db.QueryRow(ctx, userCompetenceCreateWithoutEntry,
		arg.Level,
		arg.UserID,
		arg.CompetenceID,
		arg.CreatedBy,
		arg.OrganisationID,
	)
	var i UserCompetence
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.UserID,
		&i.EntryID,
		&i.CompetenceID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.OrganisationID,
	)
	return i, err
}

const userCompetenceFind = `-- name: UserCompetenceFind :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE organisation_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UserCompetenceFind(ctx context.Context, organisationID string) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceFind, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceFindByEntryAndUser = `-- name: UserCompetenceFindByEntryAndUser :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE entry_id = $1
  AND user_id = $2
  AND organisation_id = $3
  AND deleted_at IS NULL
ORDER BY competence_id DESC
`

type UserCompetenceFindByEntryAndUserParams struct {
	EntryID        pgtype.Text `db:"entry_id"`
	UserID         string      `db:"user_id"`
	OrganisationID string      `db:"organisation_id"`
}

func (q *Queries) UserCompetenceFindByEntryAndUser(ctx context.Context, arg UserCompetenceFindByEntryAndUserParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceFindByEntryAndUser, arg.EntryID, arg.UserID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceFindByEntryID = `-- name: UserCompetenceFindByEntryID :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE entry_id = $1::text
  AND organisation_id = $2
  AND deleted_at IS NULL
ORDER BY competence_id DESC
`

type UserCompetenceFindByEntryIDParams struct {
	EntryID        string `db:"entry_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) UserCompetenceFindByEntryID(ctx context.Context, arg UserCompetenceFindByEntryIDParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceFindByEntryID, arg.EntryID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceFindByUserIDForReport = `-- name: UserCompetenceFindByUserIDForReport :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE user_id = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
  AND created_at >= $3
  AND created_at <= (($4::timestamptz)::DATE + 1)
ORDER BY created_at DESC
`

type UserCompetenceFindByUserIDForReportParams struct {
	UserID         string    `db:"user_id"`
	OrganisationID string    `db:"organisation_id"`
	From           time.Time `db:"_from"`
	To             time.Time `db:"_to"`
}

func (q *Queries) UserCompetenceFindByUserIDForReport(ctx context.Context, arg UserCompetenceFindByUserIDForReportParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceFindByUserIDForReport,
		arg.UserID,
		arg.OrganisationID,
		arg.From,
		arg.To,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceFindByUserIdAndCompetenceID = `-- name: UserCompetenceFindByUserIdAndCompetenceID :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE user_id = $1
  AND competence_id = $2
  AND organisation_id = $3
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type UserCompetenceFindByUserIdAndCompetenceIDParams struct {
	UserID         string `db:"user_id"`
	CompetenceID   string `db:"competence_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) UserCompetenceFindByUserIdAndCompetenceID(ctx context.Context, arg UserCompetenceFindByUserIdAndCompetenceIDParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceFindByUserIdAndCompetenceID, arg.UserID, arg.CompetenceID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceForCompetenceReport = `-- name: UserCompetenceForCompetenceReport :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE user_id = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
  AND created_at >= $3
  AND created_at <= (DATE $4 + 1)
ORDER BY created_at DESC
`

type UserCompetenceForCompetenceReportParams struct {
	UserID         string    `db:"user_id"`
	OrganisationID string    `db:"organisation_id"`
	StartDate      time.Time `db:"start_date"`
	EndDate        time.Time `db:"+end_date"`
}

func (q *Queries) UserCompetenceForCompetenceReport(ctx context.Context, arg UserCompetenceForCompetenceReportParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceForCompetenceReport,
		arg.UserID,
		arg.OrganisationID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceSoftDeleteByCompetenceAndEntry = `-- name: UserCompetenceSoftDeleteByCompetenceAndEntry :many
UPDATE user_competences
SET deleted_at = NOW()
WHERE competence_id = $1
  AND entry_id = $2::text
  AND organisation_id = $3
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetenceSoftDeleteByCompetenceAndEntryParams struct {
	CompetenceID   string `db:"competence_id"`
	EntryID        string `db:"entry_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) UserCompetenceSoftDeleteByCompetenceAndEntry(ctx context.Context, arg UserCompetenceSoftDeleteByCompetenceAndEntryParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceSoftDeleteByCompetenceAndEntry, arg.CompetenceID, arg.EntryID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceSoftDeleteByUserAndEntry = `-- name: UserCompetenceSoftDeleteByUserAndEntry :many
UPDATE user_competences
SET deleted_at = NOW()
WHERE user_id = $1
  AND entry_id = $2::text
  AND organisation_id = $3
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetenceSoftDeleteByUserAndEntryParams struct {
	UserID         string `db:"user_id"`
	EntryID        string `db:"entry_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) UserCompetenceSoftDeleteByUserAndEntry(ctx context.Context, arg UserCompetenceSoftDeleteByUserAndEntryParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceSoftDeleteByUserAndEntry, arg.UserID, arg.EntryID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceUpdateLevels = `-- name: UserCompetenceUpdateLevels :many
UPDATE user_competences
SET level = $1
WHERE competence_id = $2
  AND entry_id = $3::text
  AND organisation_id = $4
  AND deleted_at IS NULL
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetenceUpdateLevelsParams struct {
	Level          int32  `db:"level"`
	CompetenceID   string `db:"competence_id"`
	EntryID        string `db:"entry_id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) UserCompetenceUpdateLevels(ctx context.Context, arg UserCompetenceUpdateLevelsParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetenceUpdateLevels,
		arg.Level,
		arg.CompetenceID,
		arg.EntryID,
		arg.OrganisationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetenceUpsert = `-- name: UserCompetenceUpsert :one
INSERT INTO user_competences (entry_id, organisation_id, competence_id, level, user_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, competence_id, entry_id) DO UPDATE SET deleted_at = NULL AND level = $4
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetenceUpsertParams struct {
	EntryID        pgtype.Text `db:"entry_id"`
	OrganisationID string      `db:"organisation_id"`
	CompetenceID   string      `db:"competence_id"`
	Level          int32       `db:"level"`
	UserID         string      `db:"user_id"`
}

func (q *Queries) UserCompetenceUpsert(ctx context.Context, arg UserCompetenceUpsertParams) (UserCompetence, error) {
	row := q.db.QueryRow(ctx, userCompetenceUpsert,
		arg.EntryID,
		arg.OrganisationID,
		arg.CompetenceID,
		arg.Level,
		arg.UserID,
	)
	var i UserCompetence
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.UserID,
		&i.EntryID,
		&i.CompetenceID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.OrganisationID,
	)
	return i, err
}

const userCompetencesAll = `-- name: UserCompetencesAll :many
SELECT id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
FROM user_competences
WHERE organisation_id = $1
`

func (q *Queries) UserCompetencesAll(ctx context.Context, organisationID string) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetencesAll, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetencesSoftDeleteByEntry = `-- name: UserCompetencesSoftDeleteByEntry :many
UPDATE user_competences
SET deleted_at = NOW()
WHERE entry_id = $1
  AND organisation_id = $2
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetencesSoftDeleteByEntryParams struct {
	EntryID        pgtype.Text `db:"entry_id"`
	OrganisationID string      `db:"organisation_id"`
}

func (q *Queries) UserCompetencesSoftDeleteByEntry(ctx context.Context, arg UserCompetencesSoftDeleteByEntryParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetencesSoftDeleteByEntry, arg.EntryID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCompetencesSoftDeleteByUserAndEntry = `-- name: UserCompetencesSoftDeleteByUserAndEntry :many
UPDATE user_competences
SET deleted_at = NOW()
WHERE user_id = $1
  AND entry_id = $2
  AND organisation_id = $3
RETURNING id, level, user_id, entry_id, competence_id, created_at, created_by, deleted_at, organisation_id
`

type UserCompetencesSoftDeleteByUserAndEntryParams struct {
	UserID         string      `db:"user_id"`
	EntryID        pgtype.Text `db:"entry_id"`
	OrganisationID string      `db:"organisation_id"`
}

func (q *Queries) UserCompetencesSoftDeleteByUserAndEntry(ctx context.Context, arg UserCompetencesSoftDeleteByUserAndEntryParams) ([]UserCompetence, error) {
	rows, err := q.db.Query(ctx, userCompetencesSoftDeleteByUserAndEntry, arg.UserID, arg.EntryID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompetence
	for rows.Next() {
		var i UserCompetence
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.UserID,
			&i.EntryID,
			&i.CompetenceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
