name: "dokedu-offline"

services:
  postgres:
    image: postgres:17-alpine
    restart: no
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
