// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tag.sql

package db

import (
	"context"
)

const tagById = `-- name: TagById :one
SELECT id, name, color, organisation_id, created_at, deleted_at
FROM tags
WHERE id = $1 AND organisation_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type TagByIdParams struct {
	ID             string `db:"id"`
	OrganisationID string `db:"organisation_id"`
}

func (q *Queries) TagById(ctx context.Context, arg TagByIdParams) (Tag, error) {
	row := q.db.QueryRow(ctx, tagById, arg.ID, arg.OrganisationID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
